export default {
  CDIsi: { value: null, units: 'mg/kg-d', desc: 'soil ingestion dose' },
  CDIinhal: { value: null, units: 'mg/m3', desc: 'particulate inhalation dose' },
  CDIderm: { value: null, units: 'mg/kg-d', desc: 'dermal contact with contaminated soil dose' },
  CDIwater: { value: null, units: 'mg/kg-d', desc: 'water ingestion dose' },
  CDIfish: { value: null, units: 'mg/kg-d', desc: 'fish ingestion dose' },
  CDIprod: { value: null, units: 'mg/kg-d', desc: 'produce ingestion dose' },
  CDIpltry: { value: null, units: 'mg/kg-d', desc: 'poultry ingestion dose' },
  EF: { value: null, units: 'days/year', desc: 'exposure frequency' },
  ET: { value: null, units: 'fraction of day (hours exposed/24)', desc: 'exposure time' },
  ED: { value: null, units: 'years', desc: 'exposure duration' },
  AT: { value: null, units: 'days', desc: 'averaging time (365 days*ED)' },
  BW: { value: null, units: 'kg', desc: 'body weight' },
  SA: { value: null, units: 'cm2/day', desc: 'surface area' },
  AF: { value: null, units: 'mg/cm2', desc: 'soil adherence factor' },
  LT: { value: null, units: 'days/year', desc: 'exposure frequency' },
  IRs: { value: null, units: 'mg/day', desc: 'ingestion rate soil' },
  IRwater: { value: null, units: 'L/day', desc: 'intake rate of water' },
  IRfish: { value: null, units: 'mg/day', desc: 'intake rate of fish' },
  IRprod: { value: null, units: 'mg/day', desc: 'intake rate of produce' },
  IRpltry: { value: null, units: 'mg/day', desc: 'intake rate of poultry' },
  Csoil: { value: 0.000774, units: 'mg/kg', desc: 'concentration in soil (dry weight)' },
  Cwater: { value: 0.000014, units: 'ug/L', desc: 'water concentration (total)' },
  Cfish: { value: 0.00000000108, units: 'mg/kg fresh weight', desc: 'fish tissue concentrations' },
  Cprod: { value: 0.0000000997, units: 'mg/kg fresh weight', desc: 'concentration in produce' },
  Cpltry: { value: 0.000000273, units: 'mg/kg fresh weight', desc: 'concentration in poultry' },
  VF: { value: 1960000, units: 'm3/kg', desc: 'volatilization factor' },
  PEF: { value: 1360000000, units: 'm3/kg', desc: 'particulate emission factor' },
  ABSd: { value: 0.03, units: 'proportion', desc: 'dermal absorption' },
  RBA: { value: 1, units: 'unitless', desc: 'relative bioavailability factor for soil' },
  CFfish: { value: 1, units: 'proportion', desc: 'contaminated fraction of fish' },
  CFprod: { value: 1, units: 'proportion', desc: 'contaminated fraction of produce' },
  CFpltry: { value: 1, units: 'proportion', desc: 'contaminated fraction of poultry' },
  TVoral: { value: 0.0000000007, units: 'mg/kg-d', desc: '' },
  TVinhal: { value: 0.00000004, units: 'mg/m3', desc: '' },
  HQsi: { value: null, units: 'mg/kg-d', desc: 'soil ingestion dose' },
  HQinhal: { value: null, units: 'mg/kg-d', desc: 'particulate inhalation dose' },
  HQderm: { value: null, units: 'mg/kg-d', desc: 'dermal contact with contaminated soil dose' },
  HQwater: { value: null, units: 'mg/kg-d', desc: 'water ingestion dose' },
  HQfish: { value: null, units: 'mg/kg-d', desc: 'fish ingestion dose' },
  HQprod: { value: null, units: 'mg/kg-d', desc: 'produce ingestion dose' },
  HQpltry: { value: null, units: 'mg/kg-d', desc: 'poultry ingestion dose' },
  data: {
    EF: [350, 350, 225, 250, 75, 75],
    ED: [6, 26, 25, 1, 6, 26],
    ET: [1, 1, 0.33, 0.33, 0.0416, 0.0416],
    AT: [2190, 9490, 9125, 350, 2190, 9490],
    BW: [15, 80, 80, 80, 15, 80],
    IRs: [200, 100, 100, 330, 200, 100],
    SA: [2337, 6032, 3527, 3527, 2337, 6032],
    AF: [0.2, 0.07, 0.12, 0.3, 0.2, 0.07],
    LT: [70, 70, 70, 70, 70, 70],
    IRfish: [19500, 54000],
    IRprod: [109800, 302500],
    IRpltry: [11550, 61600],
    IRwater: [0.78, 2.5, null, null, 0.12, 0.071]
  },
  chemical: 'TCDD, 2,3,7,8-'
}
