export default {
  CDIsi: { value: null, units: 'mg/kg-d', desc: 'soil ingestion dose' },
  CDIinhal: { value: null, units: 'mg/kg-d', desc: 'particulate inhalation dose' },
  CDIderm: { value: null, units: 'mg/kg-d', desc: 'dermal contact with contaminated soil dose' },
  CDIwater: { value: null, units: 'mg/kg-d', desc: 'water ingestion dose' },
  CDIfish: { value: null, units: 'mg/kg-d', desc: 'fish ingestion dose' },
  CDIprod: { value: null, units: 'mg/kg-d', desc: 'produce ingestion dose' },
  CDIbeef: { value: null, units: 'mg/kg-d', desc: 'beef ingestion dose' },
  EF: { value: null, units: 'days/year', desc: 'exposure frequency' },
  ET: { value: null, units: 'days/year', desc: 'exposure frequency' },
  ED: { value: null, units: 'years', desc: 'exposure duration' },
  AT: { value: null, units: 'days', desc: 'averaging time (365 days*ED)' },
  BW: { value: null, units: 'kg', desc: 'body weight' },
  IRs: { value: null, units: 'mg/day', desc: 'ingestion rate soil' },
  IRw: { value: null, units: 'L/day', desc: 'intake rate of water' },
  SA: { value: null, units: 'cm2/day', desc: 'surface area' },
  AF: { value: null, units: 'mg/cm2', desc: 'soil adherence factor' },
  IRfish: { value: null, units: 'mg/day', desc: 'intake rate of fish' },
  IRprod: { value: null, units: 'mg/day', desc: 'intake rate of produce' },
  IRbeef: { value: null, units: 'mg/day', desc: 'intake rate of beef' },
  Csoil: { value: 0.000774, units: 'mg/kg', desc: 'concentration in soil (dry weight)' },
  Cwater: { value: 0.000014, units: 'ug/L', desc: 'water concentration (total)' },
  Cfish: { value: 0.00000000108, units: 'mg/kg fresh weight', desc: 'fish tissue concentrations' },
  Cprod: { value: 0.0000000997, units: 'mg/kg fresh weight', desc: 'concentration in produce' },
  Cbeef: { value: 0.000000273, units: 'mg/kg fresh weight', desc: 'concentration in beef' },
  VFs: { value: 1960000, units: 'm3/kg', desc: 'volatilization factor' },
  PEFw: { value: 1360000000, units: 'm3/kg', desc: 'particulate emission factor' },
  ABSd: { value: 0.03, units: 'proportion', desc: 'dermal absorption' },
  RBA: { value: 1, units: 'unitless', desc: 'relative bioavailability factor for soil' },
  CFfish: { value: 1, units: 'proportion', desc: 'contaminated fraction of fish' },
  CFprod: { value: 1, units: 'proportion', desc: 'contaminated fraction of produce' },
  CFbeef: { value: 1, units: 'proportion', desc: 'contaminated fraction of beef' },
  TVoral: { value: 0.0000000007, units: '', desc: '' },
  TVinhal: { value: 0.00000004, units: '', desc: '' }
}
